CREATE TABLE CLIENTS(
CPR INT NOT NULL  ,
FNAME VARCHAR(20),
LNAME VARCHAR(20),
EMAIL VARCHAR(40),
ADDRES VARCHAR(40),
BDAY INT,
BMONTH INT,
BYEAR INT,
PRIMARY KEY (CPR));

CREATE TABLE ROOMS(
NUMBER INT,
TYPE VARCHAR(20),
PRIMARY KEY (NUMBER));


CREATE TABLE RESERVATION(
ROOMNUMBER INT,
RESERVATIONNUMBER SERIAL,
CPR INT,
INDAY INT,
INMONTH INT,
INYEAR INT,
OUTDAY INT,
OUTMONTH INT,
OUTYEAR INT,
PRIMARY KEY (RESERVATIONNUMdBER),
FOREIGN KEY (CPR) REFERENCES  clients(CPR));

CREATE TABLE OTHERPEOPLE(
FNAME VARCHAR(20),
LNAME VARCHAR(20),
RESERVATIONNUM INT,
bday int,
bmonth int,
byear int,
FOREIGN KEY (RESERVATIONNUM) REFERENCES RESERVATION(RESERVATIONNUMBER));

-- ALTER TABLE OTHERPEOPLE ADD CONSTRAINT FK_RESNUMBER FOREIGN KEY(RESERVATIONNUM)
-- REFERENCES RESERVATION(RESERVATIONNUMBER) ON UPDATE CASCADE ON DELETE SET NULL;
-- 
-- ALTER TABLE ROOMAVAILABLE
-- ADD CONSTRAINT FK_NUMBER FOREIGN KEY(ROOMNUMBER)
-- REFERENCES ROOMS(NUMBER) ON UPDATE CASCADE ON DELETE SET NULL;

INSERT INTO ROOMS(NUMBER,TYPE) VALUES(101,'Single');
INSERT INTO ROOMS(NUMBER,TYPE) VALUES(102,'Single');
INSERT INTO ROOMS(NUMBER,TYPE) VALUES(103,'Single');
INSERT INTO ROOMS(NUMBER,TYPE) VALUES(104,'Double');
INSERT INTO ROOMS(NUMBER,TYPE) VALUES(105,'Double');
INSERT INTO ROOMS(NUMBER,TYPE) VALUES(106,'Double');
INSERT INTO ROOMS(NUMBER,TYPE) VALUES(107,'Apartment');
INSERT INTO ROOMS(NUMBER,TYPE) VALUES(108,'Apartment');
INSERT INTO ROOMS(NUMBER,TYPE) VALUES(109,'Apartment');



